name-template: '$RESOLVED_VERSION 🚀'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'fix'
      - 'bugfix'
  default: patch
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    title:
      - '/fix/i'
    body:
      - '/fix/i'
  - label: 'enhancement'
    title:
      - '/feature/i'
      - '/feat/i'
    body:
      - '/feature/i'
      - '/feat/i'
template: |
  ## Changes

  $CHANGES
